"""add_analyze_fields

Revision ID: 3
Revises: 2
Create Date: 2026-02-25 07:55:01.796392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3'
down_revision: Union[str, Sequence[str], None] = '2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    event_type_enum = sa.Enum('IO', 'CPU', 'MIXED', name='eventtype')
    event_type_enum.create(op.get_bind()) 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('number_consumers', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('tasks_types', event_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'tasks_types')
    op.drop_column('events', 'number_consumers')
    sa.Enum(name='eventtype').drop(op.get_bind())
    # ### end Alembic commands ###
