"""upgrade model for using

Revision ID: 4
Revises: 3
Create Date: 2026-02-28 18:31:51.475217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4'
down_revision: Union[str, Sequence[str], None] = '3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE eventstatus AS ENUM('PROCESSED', 'FAILED', 'READ')")
    op.execute("ALTER TABLE events ALTER COLUMN status TYPE eventstatus USING status::text::eventstatus")
    op.add_column('events', sa.Column('from_service', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('to_user_login', sa.String(length=64), nullable=False))
    op.add_column('events', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_events_to_user_login'), 'events', ['to_user_login'], unique=False)
    op.drop_column('events', 'number_consumers')
    op.drop_column('events', 'error_payload')
    op.drop_column('events', 'tasks_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tasks_types', postgresql.ENUM('IO', 'CPU', 'MIXED', name='eventtype'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('error_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('number_consumers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_to_user_login'), table_name='events')
    op.drop_column('events', 'read_at')
    op.drop_column('events', 'to_user_login')
    op.drop_column('events', 'from_service')
    op.execute(
        "ALTER TABLE events ALTER COLUMN status TYPE VARCHAR "
        "USING status::text"
    )
    op.execute("DROP TYPE eventstatus")
    # ### end Alembic commands ###
